export type SchemaNodeKind = "model" | "enum";

export type SchemaField = {
  name: string;
  type: string;
  detail?: string;
};

export type SchemaNode = {
  id: string;
  label: string;
  kind: SchemaNodeKind;
  section: string;
  x: number;
  y: number;
  width: number;
  height: number;
  fields?: SchemaField[];
  values?: string[];
  mapName?: string;
  accent: string;
};

export type SchemaEdge = {
  id: string;
  source: string;
  target: string;
  label: string;
  dashed?: boolean;
};

export const diagramTitle = "Smart Job Matching ERD";

export const diagramSubtitle =
  "A view of the Prisma schema that powers onboarding, jobs, applications, matches, and admin review.";

export const diagramSize = {
  width: 2060,
  height: 1580,
};

const accents = {
  auth: "#c2652a",
  onboarding: "#8c3c3c",
  marketplace: "#2457d6",
  system: "#6b5b95",
  enum: "#0b7a75",
};

export const schemaNodes: SchemaNode[] = [
  {
    id: "user",
    label: "User",
    kind: "model",
    section: "Identity",
    x: 60,
    y: 100,
    width: 320,
    height: 440,
    mapName: "user",
    accent: accents.auth,
    fields: [
      { name: "id", type: "String @id @default(uuid())" },
      { name: "name", type: "String" },
      { name: "email", type: "String @unique" },
      { name: "password", type: "String?" },
      { name: "role", type: "Role @default(USER)" },
      { name: "isActive", type: "Boolean @default(true)" },
      { name: "createdAt", type: "DateTime @default(now())" },
      { name: "emailVerified", type: "Boolean @default(true)" },
      { name: "image", type: "String?" },
      { name: "updatedAt", type: "DateTime @updatedAt" },
      { name: "jobSeeker", type: "JobSeeker?" },
      { name: "employer", type: "Employer?" },
      { name: "jobSeekerOnboarding", type: "JobSeekerOnboarding?" },
      { name: "employerOnboarding", type: "EmployerOnboarding?" },
      { name: "mediaAssets", type: "MediaAsset[]" },
      { name: "sessions", type: "Session[]" },
      { name: "accounts", type: "Account[]" },
    ],
  },
  {
    id: "session",
    label: "Session",
    kind: "model",
    section: "Auth",
    x: 430,
    y: 60,
    width: 320,
    height: 310,
    mapName: "session",
    accent: accents.auth,
    fields: [
      { name: "id", type: "String @id" },
      { name: "expiresAt", type: "DateTime" },
      { name: "token", type: "String @unique" },
      { name: "createdAt", type: "DateTime @default(now())" },
      { name: "updatedAt", type: "DateTime @updatedAt" },
      { name: "ipAddress", type: "String?" },
      { name: "userAgent", type: "String?" },
      { name: "userId", type: "String @index" },
      { name: "user", type: "User" },
    ],
  },
  {
    id: "account",
    label: "Account",
    kind: "model",
    section: "Auth",
    x: 430,
    y: 410,
    width: 320,
    height: 370,
    mapName: "account",
    accent: accents.auth,
    fields: [
      { name: "id", type: "String @id" },
      { name: "accountId", type: "String" },
      { name: "providerId", type: "String" },
      { name: "userId", type: "String @index" },
      { name: "user", type: "User" },
      { name: "accessToken", type: "String?" },
      { name: "refreshToken", type: "String?" },
      { name: "idToken", type: "String?" },
      { name: "accessTokenExpiresAt", type: "DateTime?" },
      { name: "refreshTokenExpiresAt", type: "DateTime?" },
      { name: "scope", type: "String?" },
      { name: "password", type: "String?" },
      { name: "createdAt", type: "DateTime @default(now())" },
      { name: "updatedAt", type: "DateTime @updatedAt" },
    ],
  },
  {
    id: "media-asset",
    label: "MediaAsset",
    kind: "model",
    section: "Assets",
    x: 430,
    y: 820,
    width: 320,
    height: 360,
    accent: accents.auth,
    fields: [
      { name: "id", type: "String @id @default(cuid())" },
      { name: "provider", type: "String @default(CLOUDINARY)" },
      { name: "publicId", type: "String?" },
      { name: "url", type: "String" },
      { name: "secureUrl", type: "String?" },
      { name: "format", type: "String?" },
      { name: "width", type: "Int?" },
      { name: "height", type: "Int?" },
      { name: "bytes", type: "Int?" },
      { name: "folder", type: "String?" },
      { name: "createdById", type: "String?" },
      { name: "createdBy", type: "User?" },
      { name: "createdAt", type: "DateTime @default(now())" },
    ],
  },
  {
    id: "job-seeker-onboarding",
    label: "JobSeekerOnboarding",
    kind: "model",
    section: "Onboarding",
    x: 800,
    y: 60,
    width: 360,
    height: 470,
    accent: accents.onboarding,
    fields: [
      { name: "id", type: "String @id @default(uuid())" },
      { name: "userId", type: "String @unique" },
      { name: "currentStep", type: "Int @default(0)" },
      { name: "currentStepKey", type: "String @default(identity)" },
      { name: "status", type: "OnboardingStatus @default(IN_PROGRESS)" },
      {
        name: "verificationStatus",
        type: "VerificationStatus @default(PENDING)",
      },
      { name: "draftData", type: "Json?" },
      { name: "identityData", type: "Json?" },
      { name: "experienceData", type: "Json?" },
      { name: "qualificationData", type: "Json?" },
      { name: "reviewData", type: "Json?" },
      { name: "completedAt", type: "DateTime?" },
      { name: "createdAt", type: "DateTime @default(now())" },
      { name: "updatedAt", type: "DateTime @updatedAt" },
      { name: "user", type: "User" },
    ],
  },
  {
    id: "employer-onboarding",
    label: "EmployerOnboarding",
    kind: "model",
    section: "Onboarding",
    x: 800,
    y: 610,
    width: 360,
    height: 450,
    accent: accents.onboarding,
    fields: [
      { name: "id", type: "String @id @default(uuid())" },
      { name: "userId", type: "String @unique" },
      { name: "currentStep", type: "Int @default(0)" },
      { name: "currentStepKey", type: "String @default(welcome)" },
      { name: "status", type: "OnboardingStatus @default(IN_PROGRESS)" },
      {
        name: "verificationStatus",
        type: "VerificationStatus @default(PENDING)",
      },
      { name: "draftData", type: "Json?" },
      { name: "basicInfoData", type: "Json?" },
      { name: "verificationData", type: "Json?" },
      { name: "teamSetupData", type: "Json?" },
      { name: "reviewData", type: "Json?" },
      { name: "completedAt", type: "DateTime?" },
      { name: "createdAt", type: "DateTime @default(now())" },
      { name: "updatedAt", type: "DateTime @updatedAt" },
      { name: "user", type: "User" },
    ],
  },
  {
    id: "job-seeker",
    label: "JobSeeker",
    kind: "model",
    section: "Profiles",
    x: 1200,
    y: 160,
    width: 320,
    height: 280,
    accent: accents.marketplace,
    fields: [
      { name: "id", type: "String @id @default(uuid())" },
      { name: "userId", type: "String @unique" },
      { name: "qualification", type: "QualificationLevel" },
      { name: "skills", type: "String[]" },
      { name: "createdAt", type: "DateTime @default(now())" },
      { name: "user", type: "User" },
      { name: "applications", type: "Application[]" },
      { name: "matches", type: "Match[]" },
    ],
  },
  {
    id: "employer",
    label: "Employer",
    kind: "model",
    section: "Profiles",
    x: 1200,
    y: 520,
    width: 320,
    height: 260,
    accent: accents.marketplace,
    fields: [
      { name: "id", type: "String @id @default(uuid())" },
      { name: "userId", type: "String @unique" },
      { name: "companyName", type: "String?" },
      { name: "role", type: "Role @default(USER)" },
      { name: "user", type: "User" },
      { name: "jobs", type: "Job[]" },
    ],
  },
  {
    id: "job",
    label: "Job",
    kind: "model",
    section: "Marketplace",
    x: 1600,
    y: 260,
    width: 340,
    height: 360,
    accent: accents.marketplace,
    fields: [
      { name: "id", type: "String @id @default(uuid())" },
      { name: "employerId", type: "String" },
      { name: "title", type: "String" },
      { name: "description", type: "String" },
      { name: "location", type: "String?" },
      { name: "requiredQualification", type: "QualificationLevel" },
      { name: "requiredSkills", type: "String[] @default([])" },
      { name: "createdAt", type: "DateTime @default(now())" },
      { name: "employer", type: "Employer" },
      { name: "applications", type: "Application[]" },
      { name: "matches", type: "Match[]" },
    ],
  },
  {
    id: "application",
    label: "Application",
    kind: "model",
    section: "Hiring",
    x: 1600,
    y: 700,
    width: 340,
    height: 300,
    accent: accents.marketplace,
    fields: [
      { name: "id", type: "String @id @default(uuid())" },
      { name: "jobId", type: "String" },
      { name: "seekerId", type: "String" },
      { name: "status", type: "ApplicationStatus @default(PENDING)" },
      { name: "createdAt", type: "DateTime @default(now())" },
      { name: "updatedAt", type: "DateTime @updatedAt" },
      { name: "job", type: "Job" },
      { name: "jobSeeker", type: "JobSeeker" },
      { name: "interview", type: "Interview?" },
    ],
  },
  {
    id: "match",
    label: "Match",
    kind: "model",
    section: "Hiring",
    x: 1600,
    y: 1080,
    width: 340,
    height: 280,
    accent: accents.marketplace,
    fields: [
      { name: "id", type: "String @id @default(uuid())" },
      { name: "jobId", type: "String" },
      { name: "seekerId", type: "String" },
      { name: "score", type: "Float 0-100" },
      { name: "matchType", type: "String" },
      { name: "createdAt", type: "DateTime @default(now())" },
      { name: "job", type: "Job" },
      { name: "jobSeeker", type: "JobSeeker" },
    ],
  },
  {
    id: "interview",
    label: "Interview",
    kind: "model",
    section: "Hiring",
    x: 560,
    y: 1160,
    width: 340,
    height: 260,
    accent: accents.marketplace,
    fields: [
      { name: "id", type: "String @id @default(uuid())" },
      { name: "applicationId", type: "String @unique" },
      { name: "date", type: "DateTime" },
      { name: "location", type: "String" },
      { name: "notes", type: "String?" },
      { name: "createdAt", type: "DateTime @default(now())" },
      { name: "updatedAt", type: "DateTime @updatedAt" },
      { name: "application", type: "Application" },
    ],
  },
  {
    id: "algorithm-config",
    label: "AlgorithmConfig",
    kind: "model",
    section: "System",
    x: 60,
    y: 610,
    width: 320,
    height: 360,
    mapName: "algorithm_config",
    accent: accents.system,
    fields: [
      { name: "id", type: "String @id @default(uuid())" },
      { name: "qualificationWeight", type: "Int" },
      { name: "skillsWeight", type: "Int" },
      { name: "experienceWeight", type: "Int" },
      { name: "preferenceWeight", type: "Int" },
      { name: "strictQualification", type: "Boolean @default(true)" },
      { name: "allowOverqualified", type: "Boolean @default(true)" },
      { name: "allowUnderqualified", type: "Boolean @default(false)" },
      { name: "minimumSkillMatchPercent", type: "Int @default(40)" },
      { name: "createdAt", type: "DateTime @default(now())" },
      { name: "updatedAt", type: "DateTime @updatedAt" },
    ],
  },
  {
    id: "verification",
    label: "Verification",
    kind: "model",
    section: "Auth",
    x: 60,
    y: 1040,
    width: 320,
    height: 220,
    accent: accents.auth,
    fields: [
      { name: "id", type: "String @id" },
      { name: "identifier", type: "String @index" },
      { name: "value", type: "String" },
      { name: "expiresAt", type: "DateTime" },
      { name: "createdAt", type: "DateTime @default(now())" },
      { name: "updatedAt", type: "DateTime @updatedAt" },
    ],
  },
  {
    id: "role",
    label: "Role",
    kind: "enum",
    section: "Enums",
    x: 60,
    y: 1360,
    width: 220,
    height: 220,
    accent: accents.enum,
    values: ["JOB_SEEKER", "EMPLOYER", "ADMIN", "USER"],
  },
  {
    id: "qualification-level",
    label: "QualificationLevel",
    kind: "enum",
    section: "Enums",
    x: 320,
    y: 1360,
    width: 220,
    height: 260,
    accent: accents.enum,
    values: ["BECE", "WASSCE", "DIPLOMA", "DEGREE", "MASTERS", "PHD"],
  },
  {
    id: "application-status",
    label: "ApplicationStatus",
    kind: "enum",
    section: "Enums",
    x: 580,
    y: 1360,
    width: 220,
    height: 200,
    accent: accents.enum,
    values: ["PENDING", "ACCEPTED", "REJECTED"],
  },
  {
    id: "onboarding-status",
    label: "OnboardingStatus",
    kind: "enum",
    section: "Enums",
    x: 840,
    y: 1360,
    width: 240,
    height: 200,
    accent: accents.enum,
    values: ["IN_PROGRESS", "COMPLETED"],
  },
  {
    id: "verification-status",
    label: "VerificationStatus",
    kind: "enum",
    section: "Enums",
    x: 1120,
    y: 1360,
    width: 240,
    height: 220,
    accent: accents.enum,
    values: ["PENDING", "APPROVED", "REJECTED"],
  },
];

export const schemaEdges: SchemaEdge[] = [
  { id: "session-user", source: "session", target: "user", label: "userId" },
  { id: "account-user", source: "account", target: "user", label: "userId" },
  {
    id: "media-asset-user",
    source: "media-asset",
    target: "user",
    label: "createdById",
  },
  {
    id: "job-seeker-onboarding-user",
    source: "job-seeker-onboarding",
    target: "user",
    label: "userId",
  },
  {
    id: "employer-onboarding-user",
    source: "employer-onboarding",
    target: "user",
    label: "userId",
  },
  {
    id: "job-seeker-user",
    source: "job-seeker",
    target: "user",
    label: "userId",
  },
  { id: "employer-user", source: "employer", target: "user", label: "userId" },
  {
    id: "job-employer",
    source: "job",
    target: "employer",
    label: "employerId",
  },
  {
    id: "application-job",
    source: "application",
    target: "job",
    label: "jobId",
  },
  {
    id: "application-seeker",
    source: "application",
    target: "job-seeker",
    label: "seekerId",
  },
  {
    id: "interview-application",
    source: "interview",
    target: "application",
    label: "applicationId",
  },
  { id: "match-job", source: "match", target: "job", label: "jobId" },
  {
    id: "match-seeker",
    source: "match",
    target: "job-seeker",
    label: "seekerId",
  },
  {
    id: "job-seeker-qualification",
    source: "job-seeker",
    target: "qualification-level",
    label: "qualification",
    dashed: true,
  },
  {
    id: "job-qualification",
    source: "job",
    target: "qualification-level",
    label: "requiredQualification",
    dashed: true,
  },
  {
    id: "user-role",
    source: "user",
    target: "role",
    label: "role",
    dashed: true,
  },
  {
    id: "employer-role",
    source: "employer",
    target: "role",
    label: "role",
    dashed: true,
  },
  {
    id: "application-status-link",
    source: "application",
    target: "application-status",
    label: "status",
    dashed: true,
  },
  {
    id: "job-seeker-onboarding-status",
    source: "job-seeker-onboarding",
    target: "onboarding-status",
    label: "status",
    dashed: true,
  },
  {
    id: "employer-onboarding-status",
    source: "employer-onboarding",
    target: "onboarding-status",
    label: "status",
    dashed: true,
  },
  {
    id: "job-seeker-onboarding-verification",
    source: "job-seeker-onboarding",
    target: "verification-status",
    label: "verificationStatus",
    dashed: true,
  },
  {
    id: "employer-onboarding-verification",
    source: "employer-onboarding",
    target: "verification-status",
    label: "verificationStatus",
    dashed: true,
  },
];
