export type QualificationLevelOption = {
  value: string;
  label: string;
  description: string;
  gradeLevels: string[];
};

export type SkillSector = {
  id: string;
  label: string;
  description: string;
  skills: string[];
};

export const qualificationLevels: QualificationLevelOption[] = [
  {
    value: "BECE",
    label: "BECE",
    description: "Basic Education Certificate Examination",
    gradeLevels: [
      "Grade 1",
      "Grade 2",
      "Grade 3",
      "Grade 4",
      "Grade 5",
      "Grade 6",
      "Grade 7",
      "Grade 8",
      "Grade 9",
    ],
  },
  {
    value: "WASSCE",
    label: "WASSCE",
    description: "West African Senior School Certificate Examination",
    gradeLevels: [
      "6 - 10",
      "11 - 15",
      "16 - 20",
      "21 - 25",
      "26 - 30",
      "31 - 35",
      "36 - 40",
      "41 - 45",
      "46 - 50",
    ],
  },
  {
    value: "DIPLOMA",
    label: "Diploma",
    description: "Diploma and higher national diploma pathways",
    gradeLevels: ["Distinction", "Credit", "Pass", "Referral"],
  },
  {
    value: "DEGREE",
    label: "Degree",
    description: "Undergraduate degree classification system",
    gradeLevels: [
      "First Class",
      "Second Class Upper",
      "Second Class Lower",
      "Third Class",
      "Pass",
    ],
  },
  {
    value: "MASTERS",
    label: "Masters",
    description: "Postgraduate taught or research qualification",
    gradeLevels: ["Distinction", "Merit", "Pass"],
  },
  {
    value: "PHD",
    label: "PhD",
    description: "Doctoral qualification",
    gradeLevels: ["Awarded", "In Progress", "Completed"],
  },
];

export const skillSectors: SkillSector[] = [
  {
    id: "technology",
    label: "Technology",
    description: "Software, cloud, product, and IT operations roles.",
    skills: [
      "Frontend Development",
      "Backend Development",
      "Full-Stack Development",
      "Mobile App Development",
      "DevOps",
      "Cloud Architecture",
      "Cybersecurity",
      "Systems Administration",
      "Product Management",
      "Quality Assurance",
      "Technical Support",
      "IT Project Management",
    ],
  },
  {
    id: "data-ai",
    label: "Data & AI",
    description: "Analytics, machine learning, and decision intelligence.",
    skills: [
      "Data Analysis",
      "Data Engineering",
      "Data Science",
      "Machine Learning",
      "Business Intelligence",
      "SQL Modeling",
      "ETL Pipelines",
      "Dashboard Design",
      "Prompt Engineering",
      "MLOps",
      "Statistical Analysis",
      "Data Governance",
    ],
  },
  {
    id: "design-creative",
    label: "Design & Creative",
    description: "Brand, visual, digital, and content creation work.",
    skills: [
      "Graphic Design",
      "UI Design",
      "UX Research",
      "Product Design",
      "Motion Design",
      "Illustration",
      "Content Strategy",
      "Copywriting",
      "Brand Strategy",
      "Creative Direction",
      "Video Editing",
      "Photography",
    ],
  },
  {
    id: "marketing-sales",
    label: "Marketing & Sales",
    description: "Growth, commercial, and customer acquisition roles.",
    skills: [
      "Digital Marketing",
      "SEO",
      "SEM",
      "Social Media Marketing",
      "Campaign Management",
      "Lead Generation",
      "Sales Strategy",
      "Account Management",
      "CRM Management",
      "Market Research",
      "Customer Success",
      "Partnership Development",
    ],
  },
  {
    id: "finance-accounting",
    label: "Finance & Accounting",
    description: "Budgeting, reporting, audit, and financial control.",
    skills: [
      "Financial Analysis",
      "Bookkeeping",
      "Accounts Payable",
      "Accounts Receivable",
      "Financial Reporting",
      "Budget Planning",
      "Tax Compliance",
      "Audit Support",
      "Payroll Management",
      "Treasury Operations",
      "Risk Analysis",
      "Cost Control",
    ],
  },
  {
    id: "healthcare",
    label: "Healthcare & Life Sciences",
    description: "Clinical, care, lab, and wellness specialties.",
    skills: [
      "Nursing Care",
      "Patient Management",
      "Clinical Documentation",
      "Pharmacy Support",
      "Medical Laboratory Work",
      "Public Health",
      "Health Education",
      "Physiotherapy",
      "Nutrition Support",
      "Medical Imaging",
      "Healthcare Administration",
      "Epidemiology",
    ],
  },
  {
    id: "education-training",
    label: "Education & Training",
    description: "Teaching, learning design, and institutional support.",
    skills: [
      "Teaching",
      "Curriculum Design",
      "Instructional Design",
      "Assessment Design",
      "Classroom Management",
      "Educational Technology",
      "Special Education",
      "Literacy Coaching",
      "Learning Facilitation",
      "Academic Advising",
      "Training Delivery",
      "Research Supervision",
    ],
  },
  {
    id: "engineering-construction",
    label: "Engineering & Construction",
    description: "Civil, mechanical, electrical, and built environment work.",
    skills: [
      "Civil Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Structural Design",
      "Project Estimation",
      "Quantity Surveying",
      "Site Supervision",
      "AutoCAD",
      "BIM Coordination",
      "Construction Safety",
      "Maintenance Planning",
      "Infrastructure Design",
    ],
  },
  {
    id: "operations-supply-chain",
    label: "Operations & Supply Chain",
    description: "Procurement, inventory, logistics, and process control.",
    skills: [
      "Operations Management",
      "Procurement",
      "Inventory Control",
      "Demand Planning",
      "Warehouse Management",
      "Logistics Coordination",
      "Supplier Relationship Management",
      "Process Improvement",
      "Quality Control",
      "Fleet Management",
      "Distribution Planning",
      "Production Scheduling",
    ],
  },
  {
    id: "hospitality-tourism",
    label: "Hospitality & Tourism",
    description: "Guest services, travel, food service, and events.",
    skills: [
      "Hotel Operations",
      "Front Desk Service",
      "Guest Relations",
      "Food and Beverage Service",
      "Event Planning",
      "Travel Coordination",
      "Housekeeping Management",
      "Reservations Management",
      "Tour Guiding",
      "Catering Operations",
      "Hospitality Sales",
      "Customer Experience",
    ],
  },
  {
    id: "agriculture-environment",
    label: "Agriculture & Environment",
    description: "Agribusiness, sustainability, and natural resources.",
    skills: [
      "Crop Production",
      "Livestock Management",
      "Agribusiness",
      "Irrigation Management",
      "Soil Science",
      "Environmental Management",
      "Climate Adaptation",
      "Extension Services",
      "Farm Management",
      "Food Safety",
      "Conservation Planning",
      "Water Resource Management",
    ],
  },
  {
    id: "public-sector",
    label: "Public Sector & Nonprofit",
    description: "Government, civic, advocacy, and development work.",
    skills: [
      "Policy Analysis",
      "Program Management",
      "Monitoring and Evaluation",
      "Grant Writing",
      "Stakeholder Engagement",
      "Public Administration",
      "Community Outreach",
      "Advocacy",
      "Research and Reporting",
      "Compliance Management",
      "Project Coordination",
      "Proposal Development",
    ],
  },
];

export const allSkills = skillSectors.flatMap((sector) => sector.skills);

export const defaultSkillSuggestions = [
  "Web Development",
  "Data Analysis",
  "Project Management",
  "Customer Experience",
  "Financial Reporting",
  "Curriculum Design",
];
