export type QualificationLevelOption = {
  value: string;
  label: string;
  description: string;
  gradeLevels: string[];
};

export type SkillSector = {
  id: string;
  label: string;
  description: string;
  skills: string[];
};

export type LocationModeOption = {
  value: "REMOTE" | "PART_TIME" | "SPECIFIC_LOCATION";
  label: string;
  description: string;
};

export type GhanaRegionOption = {
  name: string;
  towns: string[];
};

export const qualificationLevels: QualificationLevelOption[] = [
  {
    value: "BECE",
    label: "BECE",
    description: "Basic Education Certificate Examination",
    gradeLevels: [
      "Grade 1",
      "Grade 2",
      "Grade 3",
      "Grade 4",
      "Grade 5",
      "Grade 6",
      "Grade 7",
      "Grade 8",
      "Grade 9",
    ],
  },
  {
    value: "WASSCE",
    label: "WASSCE",
    description: "West African Senior School Certificate Examination",
    gradeLevels: [
      "6 - 10",
      "11 - 15",
      "16 - 20",
      "21 - 25",
      "26 - 30",
      "31 - 35",
      "36 - 40",
      "41 - 45",
      "46 - 50",
    ],
  },
  {
    value: "DIPLOMA",
    label: "Diploma",
    description: "Diploma and higher national diploma pathways",
    gradeLevels: ["Distinction", "Credit", "Pass", "Referral"],
  },
  {
    value: "DEGREE",
    label: "Degree",
    description: "Undergraduate degree classification system",
    gradeLevels: [
      "First Class",
      "Second Class Upper",
      "Second Class Lower",
      "Third Class",
      "Pass",
    ],
  },
  {
    value: "MASTERS",
    label: "Masters",
    description: "Postgraduate taught or research qualification",
    gradeLevels: ["Distinction", "Merit", "Pass"],
  },
  {
    value: "PHD",
    label: "PhD",
    description: "Doctoral qualification",
    gradeLevels: ["Awarded", "In Progress", "Completed"],
  },
];

export const locationModes: LocationModeOption[] = [
  {
    value: "REMOTE",
    label: "Remote",
    description: "Open to fully remote opportunities anywhere.",
  },
  {
    value: "PART_TIME",
    label: "Part Time",
    description: "Open to flexible, part-time or hybrid work.",
  },
  {
    value: "SPECIFIC_LOCATION",
    label: "Specific Location",
    description: "Choose a region and city, but still allow custom entry.",
  },
];

export const skillSectors: SkillSector[] = [
  {
    id: "technology",
    label: "Technology",
    description: "Software, cloud, product, and IT operations roles.",
    skills: [
      "Frontend Development",
      "Backend Development",
      "Full-Stack Development",
      "Mobile App Development",
      "DevOps",
      "Cloud Architecture",
      "Cybersecurity",
      "Systems Administration",
      "Product Management",
      "Quality Assurance",
      "Technical Support",
      "IT Project Management",
    ],
  },
  {
    id: "data-ai",
    label: "Data & AI",
    description: "Analytics, machine learning, and decision intelligence.",
    skills: [
      "Data Analysis",
      "Data Engineering",
      "Data Science",
      "Machine Learning",
      "Business Intelligence",
      "SQL Modeling",
      "ETL Pipelines",
      "Dashboard Design",
      "Prompt Engineering",
      "MLOps",
      "Statistical Analysis",
      "Data Governance",
    ],
  },
  {
    id: "design-creative",
    label: "Design & Creative",
    description: "Brand, visual, digital, and content creation work.",
    skills: [
      "Graphic Design",
      "UI Design",
      "UX Research",
      "Product Design",
      "Motion Design",
      "Illustration",
      "Content Strategy",
      "Copywriting",
      "Brand Strategy",
      "Creative Direction",
      "Video Editing",
      "Photography",
    ],
  },
  {
    id: "marketing-sales",
    label: "Marketing & Sales",
    description: "Growth, commercial, and customer acquisition roles.",
    skills: [
      "Digital Marketing",
      "SEO",
      "SEM",
      "Social Media Marketing",
      "Campaign Management",
      "Lead Generation",
      "Sales Strategy",
      "Account Management",
      "CRM Management",
      "Market Research",
      "Customer Success",
      "Partnership Development",
    ],
  },
  {
    id: "finance-accounting",
    label: "Finance & Accounting",
    description: "Budgeting, reporting, audit, and financial control.",
    skills: [
      "Financial Analysis",
      "Bookkeeping",
      "Accounts Payable",
      "Accounts Receivable",
      "Financial Reporting",
      "Budget Planning",
      "Tax Compliance",
      "Audit Support",
      "Payroll Management",
      "Treasury Operations",
      "Risk Analysis",
      "Cost Control",
    ],
  },
  {
    id: "healthcare",
    label: "Healthcare & Life Sciences",
    description: "Clinical, care, lab, and wellness specialties.",
    skills: [
      "Nursing Care",
      "Patient Management",
      "Clinical Documentation",
      "Pharmacy Support",
      "Medical Laboratory Work",
      "Public Health",
      "Health Education",
      "Physiotherapy",
      "Nutrition Support",
      "Medical Imaging",
      "Healthcare Administration",
      "Epidemiology",
    ],
  },
  {
    id: "education-training",
    label: "Education & Training",
    description: "Teaching, learning design, and institutional support.",
    skills: [
      "Teaching",
      "Curriculum Design",
      "Instructional Design",
      "Assessment Design",
      "Classroom Management",
      "Educational Technology",
      "Special Education",
      "Literacy Coaching",
      "Learning Facilitation",
      "Academic Advising",
      "Training Delivery",
      "Research Supervision",
    ],
  },
  {
    id: "engineering-construction",
    label: "Engineering & Construction",
    description: "Civil, mechanical, electrical, and built environment work.",
    skills: [
      "Civil Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Structural Design",
      "Project Estimation",
      "Quantity Surveying",
      "Site Supervision",
      "AutoCAD",
      "BIM Coordination",
      "Construction Safety",
      "Maintenance Planning",
      "Infrastructure Design",
    ],
  },
  {
    id: "operations-supply-chain",
    label: "Operations & Supply Chain",
    description: "Procurement, inventory, logistics, and process control.",
    skills: [
      "Operations Management",
      "Procurement",
      "Inventory Control",
      "Demand Planning",
      "Warehouse Management",
      "Logistics Coordination",
      "Supplier Relationship Management",
      "Process Improvement",
      "Quality Control",
      "Fleet Management",
      "Distribution Planning",
      "Production Scheduling",
    ],
  },
  {
    id: "hospitality-tourism",
    label: "Hospitality & Tourism",
    description: "Guest services, travel, food service, and events.",
    skills: [
      "Hotel Operations",
      "Front Desk Service",
      "Guest Relations",
      "Food and Beverage Service",
      "Event Planning",
      "Travel Coordination",
      "Housekeeping Management",
      "Reservations Management",
      "Tour Guiding",
      "Catering Operations",
      "Hospitality Sales",
      "Customer Experience",
    ],
  },
  {
    id: "agriculture-environment",
    label: "Agriculture & Environment",
    description: "Agribusiness, sustainability, and natural resources.",
    skills: [
      "Crop Production",
      "Livestock Management",
      "Agribusiness",
      "Irrigation Management",
      "Soil Science",
      "Environmental Management",
      "Climate Adaptation",
      "Extension Services",
      "Farm Management",
      "Food Safety",
      "Conservation Planning",
      "Water Resource Management",
    ],
  },
  {
    id: "public-sector",
    label: "Public Sector & Nonprofit",
    description: "Government, civic, advocacy, and development work.",
    skills: [
      "Policy Analysis",
      "Program Management",
      "Monitoring and Evaluation",
      "Grant Writing",
      "Stakeholder Engagement",
      "Public Administration",
      "Community Outreach",
      "Advocacy",
      "Research and Reporting",
      "Compliance Management",
      "Project Coordination",
      "Proposal Development",
    ],
  },
];

export const ghanaRegions: GhanaRegionOption[] = [
  {
    name: "Ahafo",
    towns: [
      "Goaso",
      "Kenyasi",
      "Mim",
      "Hwidiem",
      "Kukuom",
      "Sankore",
      "Duayaw Nkwanta",
      "Acherensua",
      "Hwidiem",
      "Dadiesoaba",
    ],
  },
  {
    name: "Ashanti",
    towns: [
      "Kumasi",
      "Obuasi",
      "Ejisu",
      "Bekwai",
      "Konongo",
      "Mampong",
      "Agogo",
      "Nsuta",
      "Asante Mampong",
      "New Edubiase",
    ],
  },
  {
    name: "Bono",
    towns: [
      "Sunyani",
      "Berekum",
      "Wenchi",
      "Dormaa Ahenkro",
      "Techiman",
      "Nkoranza",
      "Jaman North",
      "Banda Ahenkro",
      "Duayaw Nkwanta",
      "Sampa",
    ],
  },
  {
    name: "Bono East",
    towns: [
      "Techiman",
      "Kintampo",
      "Atebubu",
      "Nkoranza",
      "Prang",
      "Yeji",
      "Jema",
      "Aframso",
      "Kyeremasu",
      "Sekyedumase",
    ],
  },
  {
    name: "Central",
    towns: [
      "Cape Coast",
      "Elmina",
      "Kasoa",
      "Winneba",
      "Mankessim",
      "Swedru",
      "Saltpond",
      "Apam",
      "Dunkwa-on-Offin",
      "Agona Swedru",
    ],
  },
  {
    name: "Eastern",
    towns: [
      "Koforidua",
      "Nkawkaw",
      "Suhum",
      "Akosombo",
      "Akyem Oda",
      "Somanya",
      "Nsawam",
      "Begoro",
      "Tafo",
      "Donkorkrom",
    ],
  },
  {
    name: "Greater Accra",
    towns: [
      "Accra",
      "Tema",
      "Madina",
      "Adenta",
      "Teshie",
      "Ashaiman",
      "Weija",
      "Abokobi",
      "Dodowa",
      "Kasoa",
    ],
  },
  {
    name: "North East",
    towns: [
      "Nalerigu",
      "Gambaga",
      "Walewale",
      "Bunkpurugu",
      "Langbinsi",
      "Chereponi",
      "Yagaba",
      "Sakogu",
      "Gbintiri",
      "Nakpanduri",
    ],
  },
  {
    name: "Northern",
    towns: [
      "Tamale",
      "Yendi",
      "Savelugu",
      "Gushiegu",
      "Karaga",
      "Saboba",
      "Tolon",
      "Kumbungu",
      "Bole",
      "Damongo",
    ],
  },
  {
    name: "Oti",
    towns: [
      "Dambai",
      "Jasikan",
      "Nkwanta",
      "Kadjebi",
      "Kete Krachi",
      "Krachi West",
      "Biakoye",
      "Kpassa",
      "Abotoase",
      "Ahamansu",
    ],
  },
  {
    name: "Savanna",
    towns: [
      "Damongo",
      "Buipe",
      "Salaga",
      "Daboya",
      "Sawla",
      "Bole",
      "Tuna",
      "Larabanga",
      "Busunu",
      "Mankarigu",
    ],
  },
  {
    name: "Upper East",
    towns: [
      "Bolgatanga",
      "Bawku",
      "Navrongo",
      "Paga",
      "Zebilla",
      "Sandema",
      "Garu",
      "Pusiga",
      "Tempane",
      "Fumbisi",
    ],
  },
  {
    name: "Upper West",
    towns: [
      "Wa",
      "Tumu",
      "Lawra",
      "Jirapa",
      "Nandom",
      "Gwollu",
      "Hamile",
      "Funsi",
      "Kaleo",
      "Dorimon",
    ],
  },
  {
    name: "Volta",
    towns: [
      "Ho",
      "Hohoe",
      "Keta",
      "Kpando",
      "Anloga",
      "Aflao",
      "Sogakope",
      "Dzodze",
      "Peki",
      "Denu",
    ],
  },
  {
    name: "Western",
    towns: [
      "Sekondi",
      "Takoradi",
      "Tarkwa",
      "Axim",
      "Prestea",
      "Bogoso",
      "Shama",
      "Enchi",
      "Half Assini",
      "Nsuaem",
    ],
  },
  {
    name: "Western North",
    towns: [
      "Sefwi Wiawso",
      "Bibiani",
      "Juaboso",
      "Enchi",
      "Dadieso",
      "Asankragua",
      "Bodi",
      "Chirano",
      "Akontombra",
      "Sefwi Bekwai",
    ],
  },
];

const buildInstitutions = (seed: string, entries: string[]) =>
  Array.from(
    { length: 30 },
    (_, index) => entries[index] ?? `${seed} Institution ${index + 1}`,
  );

export const institutionCatalog = {
  BECE: buildInstitutions("BECE", [
    "Achimota Basic School",
    "Adisadel Basic School",
    "Mfantsipim Basic School",
    "Wesley Girls Basic School",
    "Prempeh Basic School",
    "St. Augustine Basic School",
    "Opoku Ware Basic School",
    "Holy Child Basic School",
    "Tema Community 4 Basic School",
    "Presbyterian Basic School",
  ]),
  WASSCE: buildInstitutions("WASSCE", [
    "Achimota School",
    "Adisadel College",
    "Mfantsipim School",
    "Wesley Girls High School",
    "Prempeh College",
    "St. Augustine's College",
    "Opoku Ware School",
    "Holy Child School",
    "Tema Secondary School",
    "Presbyterian Boys' Secondary School",
  ]),
  DIPLOMA: buildInstitutions("Diploma", [
    "Accra Technical University",
    "Cape Coast Technical University",
    "Kumasi Technical University",
    "Takoradi Technical University",
    "Sunyani Technical University",
    "Ho Technical University",
    "Tamale Technical University",
    "Koforidua Technical University",
    "Bolgatanga Technical University",
    "Tarkwa Technical Institute",
  ]),
  DEGREE: buildInstitutions("Degree", [
    "University of Ghana",
    "Kwame Nkrumah University of Science and Technology",
    "University of Cape Coast",
    "University of Education, Winneba",
    "University for Development Studies",
    "University of Professional Studies, Accra",
    "University of Mines and Technology",
    "University of Health and Allied Sciences",
    "University of Energy and Natural Resources",
    "Ashesi University",
  ]),
  MASTERS: buildInstitutions("Masters", [
    "University of Ghana Graduate School",
    "KNUST School of Graduate Studies",
    "University of Cape Coast School of Graduate Studies",
    "UEW School of Graduate Studies",
    "UDS School of Graduate Studies",
    "UPSA Graduate School",
    "GIMPA School of Graduate Studies",
    "Central University Graduate School",
    "Ashesi University Graduate School",
    "Valley View University Graduate School",
  ]),
  PHD: buildInstitutions("PhD", [
    "University of Ghana Doctoral College",
    "KNUST College of Graduate Studies",
    "University of Cape Coast Doctoral School",
    "UEW Doctoral School",
    "UDS Doctoral School",
    "UPSA Doctoral School",
    "GIMPA Doctoral Institute",
    "Central University Doctoral School",
    "Ashesi Research Centre",
    "University of Health and Allied Sciences Doctoral School",
  ]),
} as const;

export type InstitutionQualificationKey = keyof typeof institutionCatalog;

export const getInstitutionsForQualification = (
  qualification: string,
): string[] => {
  if (qualification in institutionCatalog) {
    return institutionCatalog[qualification as InstitutionQualificationKey];
  }

  return institutionCatalog.DEGREE;
};

export const getTownsForRegion = (region: string) =>
  ghanaRegions.find((entry) => entry.name === region)?.towns ?? [];

export const allSkills = skillSectors.flatMap((sector) => sector.skills);

export const defaultSkillSuggestions = [
  "Web Development",
  "Data Analysis",
  "Project Management",
  "Customer Experience",
  "Financial Reporting",
  "Curriculum Design",
];
